onlinexam/urls.py
from django.urls import path,include
from django.contrib import admin
from exam import views
from django.contrib.auth.views import LogoutView,LoginView
from assignment import views as assignment_views
urlpatterns = [
   
    path('admin/', admin.site.urls),
    path('teacher/',include('teacher.urls')),
    path('student/',include('student.urls')),
    


    path('',views.home_view,name=''),
    path('logout', views.custom_logout_view, name='logout'),
    path('contactus', views.contactus_view),
    path('afterlogin', views.afterlogin_view,name='afterlogin'),



    path('adminclick', views.adminclick_view),
    path('adminlogin', LoginView.as_view(template_name='exam/adminlogin.html'),name='adminlogin'),
    path('admin-dashboard', views.admin_dashboard_view,name='admin-dashboard'),
    path('admin-teacher', views.admin_teacher_view,name='admin-teacher'),
    path('admin-view-teacher', views.admin_view_teacher_view,name='admin-view-teacher'),
    path('update-teacher/<int:pk>', views.update_teacher_view,name='update-teacher'),
    path('delete-teacher/<int:pk>', views.delete_teacher_view,name='delete-teacher'),
    path('admin-view-pending-teacher', views.admin_view_pending_teacher_view,name='admin-view-pending-teacher'),
    #path('admin-view-teacher-salary', views.admin_view_teacher_salary_view,name='admin-view-teacher-salary'),
    path('approve-teacher/<int:pk>', views.approve_teacher_view,name='approve-teacher'),
    path('reject-teacher/<int:pk>', views.reject_teacher_view,name='reject-teacher'),

    path('admin-student', views.admin_student_view,name='admin-student'),
    path('admin-view-student', views.admin_view_student_view,name='admin-view-student'),
    path('admin-view-student-marks', views.admin_view_student_marks_view,name='admin-view-student-marks'),
    path('admin-view-marks/<int:pk>', views.admin_view_marks_view,name='admin-view-marks'),
    path('admin-check-marks/<int:pk>', views.admin_check_marks_view,name='admin-check-marks'),
    path('update-student/<int:pk>', views.update_student_view,name='update-student'),
    path('delete-student/<int:pk>', views.delete_student_view,name='delete-student'),

    path('admin-course', views.admin_course_view,name='admin-course'),
    path('admin-add-course', views.admin_add_course_view,name='admin-add-course'),
    path('admin-view-course', views.admin_view_course_view,name='admin-view-course'),
    path('delete-course/<int:pk>', views.delete_course_view,name='delete-course'),

    path('admin-question', views.admin_question_view,name='admin-question'),
    path('admin-add-question', views.admin_add_question_view,name='admin-add-question'),
    path('admin-view-question', views.admin_view_question_view,name='admin-view-question'),
    path('view-question/<int:pk>', views.view_question_view,name='view-question'),
    path('delete-question/<int:pk>', views.delete_question_view,name='delete-question'),

    path('admin-assignment', assignment_views.admin_assignment_view, name='admin-assignment'),
    path('admin-add-assignment', assignment_views.admin_add_assignment_view, name='admin-add-assignment'),
    path('admin-view-assignment', assignment_views.admin_view_assignment_view, name='admin-view-assignment'),
    path('admin-delete-assignment/<int:pk>/', assignment_views.admin_delete_assignment_view,name='admin-delete-assignment'),
    path('admin-view-student-grades', assignment_views.admin_view_student_grades_view,name='admin-view-student-grades'),
    path('admin-view-submissions/<int:pk>', assignment_views.admin_view_grades_view,name='admin-view-submissions'),
    path('admin-check-grades/<int:pk>', assignment_views.admin_check_grades_view,name='admin-check-grades'),

]

student/urls.py
from django.urls import path
from student import views
from django.contrib.auth.views import LoginView
from assignment import views as assignment_views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
path('studentclick', views.studentclick_view),
path('studentlogin', LoginView.as_view(template_name='student/studentlogin.html'),name='studentlogin'),
path('studentsignup', views.student_signup_view,name='studentsignup'),
path('student-dashboard', views.student_dashboard_view,name='student-dashboard'),
path('student-exam', views.student_exam_view,name='student-exam'),
path('take-exam/<int:pk>', views.take_exam_view,name='take-exam'),
path('start-exam/<int:pk>', views.start_exam_view,name='start-exam'),

path('calculate-marks', views.calculate_marks_view,name='calculate-marks'),
path('view-result', views.view_result_view,name='view-result'),
path('check-marks/<int:pk>', views.check_marks_view,name='check-marks'),
path('student-marks', views.student_marks_view,name='student-marks'),

path('student-assignment', assignment_views.student_assignment_view, name='student-assignment-view'),
path('student-submit/<int:pk>/', assignment_views.upload_submission_view, name='upload-submission'),
path('student-submissions/<int:pk>/', assignment_views.check_submission_view, name='check-submission'),
path('student-grades',assignment_views.my_marks_view,name='student-grades'),
path('view-assignment-results',assignment_views.view_assignment_results, name='view-assignment-results'),
]

teacher/urls.py
from django.urls import path
from teacher import views
from django.contrib.auth.views import LoginView
from assignment import views as assignment_views  # Import assignment views

app_name = 'teacher'
 
urlpatterns = [
path('teacherclick', views.teacherclick_view),
path('teacherlogin', LoginView.as_view(template_name='teacher/teacherlogin.html'),name='teacherlogin'),
path('teachersignup', views.teacher_signup_view,name='teachersignup'),
path('teacher-dashboard', views.teacher_dashboard_view,name='teacher-dashboard'),
path('teacher-exam', views.teacher_exam_view,name='teacher-exam'),
path('teacher-add-exam', views.teacher_add_exam_view,name='teacher-add-exam'),
path('teacher-view-exam', views.teacher_view_exam_view,name='teacher-view-exam'),
path('delete-exam/<int:pk>', views.delete_exam_view,name='delete-exam'),
path('teacher-view-student-marks/', views.teacher_view_student_marks_view, name='teacher-view-student-marks'),
path('teacher-view-marks/<int:pk>/', views.teacher_view_marks_view, name='teacher-view-marks'),
path('teacher-check-marks/<int:pk>/', views.teacher_check_marks_view, name='teacher-check-marks'),


path('teacher-question', views.teacher_question_view,name='teacher-question'),
path('teacher-add-question', views.teacher_add_question_view,name='teacher-add-question'),
path('teacher-view-question', views.teacher_view_question_view,name='teacher-view-question'),
path('see-question/<int:pk>', views.see_question_view,name='see-question'),
path('remove-question/<int:pk>', views.remove_question_view,name='remove-question'),


path('teacher-assignment', assignment_views.teacher_assignment_view, name='teacher-assignment'),
path('teacher-add-assignment', assignment_views.teacher_add_assignment_view, name='teacher-add-assignment'),
path('teacher-view-assignment', assignment_views.teacher_view_assignment_view, name='teacher-view-assignment'),
path('teacher-delete-assignment/<int:pk>/', assignment_views.teacher_delete_assignment_view,name='teacher-delete-assignment'),
path('teacher-view-submissions', assignment_views.teacher_view_submissions_view, name='teacher-view-submissions'),




]

teacher/models.py
from django.db import models
from django.contrib.auth.models import User

class Teacher(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    profile_pic= models.ImageField(upload_to='profile_pic/Teacher/',null=True,blank=True)
    address = models.CharField(max_length=40)
    mobile = models.CharField(max_length=20,null=False)
    status= models.BooleanField(default=False)
    designation = models.CharField(max_length=100, null=True, blank=True)
    @property
    def get_name(self):
        return self.user.first_name+" "+self.user.last_name
    @property
    def get_instance(self):
        return self
    def __str__(self):
        return self.user.first_name

teacher/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models

class TeacherUserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['first_name','last_name','username','password']
        widgets = {
        'password': forms.PasswordInput()
        }

class TeacherForm(forms.ModelForm):
    class Meta:
        model=models.Teacher
        fields=['address','mobile','profile_pic']

teacher/views.py
from django.shortcuts import render,redirect
from django.shortcuts import reverse
from . import forms,models
from django.contrib import messages
from django.db.models import Sum
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required,user_passes_test
from django.conf import settings
from datetime import date, timedelta
from exam import models as QMODEL
from student import models as SMODEL
from exam import forms as QFORM
from assignment.models import Assignment



#for showing signup/login button for teacher
def teacherclick_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('afterlogin')
    return render(request,'teacher/teacherclick.html')

def teacher_signup_view(request):
    userForm=forms.TeacherUserForm()
    teacherForm=forms.TeacherForm()
    mydict={'userForm':userForm,'teacherForm':teacherForm}
    if request.method=='POST':
        userForm=forms.TeacherUserForm(request.POST)
        teacherForm=forms.TeacherForm(request.POST,request.FILES)
        if userForm.is_valid() and teacherForm.is_valid():
            user=userForm.save()
            user.set_password(user.password)
            user.save()
            teacher=teacherForm.save(commit=False)
            teacher.user=user
            teacher.save()
            my_teacher_group = Group.objects.get_or_create(name='TEACHER')
            my_teacher_group[0].user_set.add(user)
        return HttpResponseRedirect('teacherlogin')
    return render(request,'teacher/teachersignup.html',context=mydict)



def is_teacher(user):
    return user.groups.filter(name='TEACHER').exists()

@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def teacher_dashboard_view(request):
    dict={
    
    'total_course':QMODEL.Course.objects.all().count(),
    'total_question':QMODEL.Question.objects.all().count(),
    'total_student':SMODEL.Student.objects.all().count(),
    'total_assignment' : Assignment.objects.filter(created_by=request.user).count(),
    }
    return render(request,'teacher/teacher_dashboard.html',context=dict)

@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def teacher_exam_view(request):
    return render(request,'teacher/teacher_exam.html')


@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
# teacher/views.py



@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def teacher_add_exam_view(request):
    courseForm = QFORM.CourseForm()
    if request.method == 'POST':
        courseForm = QFORM.CourseForm(request.POST)
        if courseForm.is_valid():        
            courseForm.save()
            messages.success(request, "Exam added successfully!")
            return HttpResponseRedirect('/teacher/teacher-view-exam')
        else:
            messages.error(request, "There was an error adding the exam. Please check the form.")
            print("form is invalid")
    return render(request, 'teacher/teacher_add_exam.html', {'courseForm': courseForm})


@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher) 
def teacher_view_exam_view(request):
    courses = QMODEL.Course.objects.all()
    return render(request,'teacher/teacher_view_exam.html',{'courses':courses})

@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def delete_exam_view(request,pk):
    course=QMODEL.Course.objects.get(id=pk)
    course.delete()
    return HttpResponseRedirect('/teacher/teacher-view-exam')

@login_required(login_url='adminlogin')
def teacher_question_view(request):
    return render(request,'teacher/teacher_question.html')

@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def teacher_add_question_view(request):
    questionForm=QFORM.QuestionForm()
    if request.method=='POST':
        questionForm=QFORM.QuestionForm(request.POST)
        if questionForm.is_valid():
            question=questionForm.save(commit=False)
            course=QMODEL.Course.objects.get(id=request.POST.get('courseID'))
            question.course=course
            question.save()       
        else:
            print("form is invalid")
        return HttpResponseRedirect('/teacher/teacher-view-question')
    return render(request,'teacher/teacher_add_question.html',{'questionForm':questionForm})

@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def teacher_view_question_view(request):
    courses= QMODEL.Course.objects.all()
    return render(request,'teacher/teacher_view_question.html',{'courses':courses})

@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def see_question_view(request,pk):
    questions=QMODEL.Question.objects.all().filter(course_id=pk)
    return render(request,'teacher/see_question.html',{'questions':questions})

@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def remove_question_view(request,pk):
    question=QMODEL.Question.objects.get(id=pk)
    question.delete()
    return HttpResponseRedirect('/teacher/teacher-view-question')

@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def teacher_view_student_marks_view(request):
    students = SMODEL.Student.objects.all()  # Retrieve all students
    return render(request, 'teacher/teacher_view_student_marks.html', {'students': students})


@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def teacher_view_marks_view(request, pk):
    courses = QMODEL.Course.objects.all()
    response =  render(request,'teacher/teacher_view_marks.html',{'courses':courses})
    response.set_cookie('student_id',str(pk))
    return response  # Retrieve all courses


@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def teacher_check_marks_view(request,pk):
    course = QMODEL.Course.objects.get(id=pk)
    student_id = request.COOKIES.get('student_id')
    student= SMODEL.Student.objects.get(id=student_id)

    results= QMODEL.ExamAttempt.objects.all().filter(exam=course).filter(student=student)
    return render(request,'teacher/teacher_check_marks.html',{'results':results})
    

templates/teacher/see_question.html
{% extends 'teacher/teacherbase.html' %}
{% block content %}
{%load static%}

<head>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

  <style media="screen">
    a:link {
      text-decoration: none;
    }

    h6 {
      text-align: center;
    }

    .row {
      margin: 100px;
    }
  </style>
</head>
<br><br>
<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h6 class="panel-title">Available Questions</h6>
    </div>
    <table class="table table-hover table-bordered" id="dev-table">
      <thead>
        <tr>

          <th>Question</th>
         
          <th>Marks</th>
          <th>Action</th>
        </tr>
      </thead>
      {% for c in questions %}
      <tr>

        <td> {{c.question}}</td>
        
        <td>{{c.marks}}</td>
        <td><a class="btn btn-danger btn-xs" style="border-radius: 0%;" href="{% url 'teacher:remove-question' c.id  %}"><span class="glyphicon glyphicon-trash"></span></a></td>
        
      </tr>
      {% endfor %}
    </table>
  </div>
</div>

<br><br><br><br><br><br>
{% endblock content %}

templates/teacher/teacher_add_question.html
{% extends 'teacher/teacherbase.html' %}
{% load widget_tweaks %}
{% block content %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
  a:link {
        text-decoration: none;
      }
    
  </style>
</head>
<h2 style="text-align:center;">Add Question</h2>
<form method="POST" autocomplete="off" style="margin:100px;margin-top: 0px;">
    {%csrf_token%}
    <div class="form-group">
        <label for="question">Course</label>
      {% render_field questionForm.courseID|attr:'required:true' class="form-control"  %}
        <br>

      <label for="question">Question</label>
      {% render_field questionForm.question|attr:'required:true' class="form-control" placeholder="Example: What is the relation calculus?" %}
        <br>
      <label for="question_number">Marks</label>
      {% render_field questionForm.marks|attr:'required:true' class="form-control" placeholder="Example: 5" %}
        <br>
      <label for="option1">Option 1</label>
      {% render_field questionForm.option1|attr:'required:true' class="form-control" placeholder="Example: It is a kind of procedural language" %}
        <br>
      <label for="option2">Option 2</label>
      {% render_field questionForm.option2|attr:'required:true' class="form-control" placeholder="Example: It is a non-procedural language" %}
        <br>
      <label for="option3">Option 3</label>
      {% render_field questionForm.option3|attr:'required:true' class="form-control" placeholder="Example: It is a high-level language" %}
        <br>
      <label for="option4">Option 4</label>
      {% render_field questionForm.option4|attr:'required:true' class="form-control" placeholder="Example: It is Data Definition language" %}
        <br>
      <label for="answer">Correct Answer</label>
      {% render_field questionForm.answer|attr:'required:true' class="form-control" %}
    </div>
    

    <button type="submit" class="btn btn-success" style="border-radius: 0%;">Submit Question</button>
  </form>
<br><br><br>
{% endblock content %}

templates/teacher/teacher_assignment.html
<!-- assignments/templates/assignments/teacher/teacher_assignment.html -->
{% extends 'teacher/teacherbase.html' %}
{% load widget_tweaks %}
{% block content %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <link href="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <style type="text/css">
      a:link {
        text-decoration: none;
      }
  
      .order-card {
        color: rgb(255, 255, 255);
      }
  
      .bg-c-blue {
        background: #04868f;
      }
  
      .bg-c-gtx {
        background:#57717d;
      }
      .bg-c-yellow {
        background: #F56565;
      }
  
      .bg-c-pink {
        background: #663a30;
      }
  
      .card {
        -webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
        box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
        margin-bottom: 30px;
        -webkit-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out;
      }
  
      .card .card-block {
        padding: 25px;
      }
  
      .order-card i {
        font-size: 26px;
      }
  
      .f-left {
        float: left;
      }
  
      .f-right {
        float: right;
      }
      header {
        left: 0px;
        right: 0px;
      }
    </style>
</head>
<br><br>

<div class="container">
  <div class="row">
    <div class="col-md-4 col-xl-6">
      <a href="{% url 'teacher:teacher-add-assignment' %}" style="text-decoration: none;color:white;">
        <div class="card bg-c-blue order-card">
          <div class="card-block">
            <h6 class="m-b-20"> Add Assignment </h6>
            <h2 class="text-right"><i class="fas fa-plus f-left"></i></h2>
          </div>
        </div>
      </a>
    </div>

    <div class="col-md-4 col-xl-6">
      <a href="{% url 'teacher:teacher-view-assignment' %}" style="text-decoration: none;color:white;">
        <div class="card bg-c-gtx order-card">
          <div class="card-block">
            <h6 class="m-b-20"> View Assignments </h6>
            <h2 class="text-right"><i class="fas fa-eye f-left"></i></h2>
          </div>
        </div>
      </a>
    </div>
    <div class="col-md-4 col-xl-6">
      <a href="{% url 'teacher:teacher-view-submissions' %}" style="text-decoration: none;color:white;">
        <div class="card bg-c-gtx order-card">
          <div class="card-block">
            <h6 class="m-b-20"> View Submissisions </h6>
            <h2 class="text-right"><i class="fas fa-eye f-left"></i></h2>
          </div>
        </div>
      </a>
    </div>
  </div>
</div>

<br><br><br><br><br><br><br><br><br><br>

<script src="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>

{% endblock content %}

templates/teacher/teacher_check_marks.html
{% extends 'teacher/teacherbase.html' %}
{% block content %}
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">

<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h6 class="panel-title">Marks for {{ course.course_name }}</h6>
    </div>
    <table class="table table-hover table-bordered">
      <thead>
        <tr>
          <th>Course</th>
          <th>Marks Obtained</th>
          <th>Exam Date</th>
        </tr>
      </thead>
      <tbody>
        {% for result in results %}
        <tr>
          <td>{{ result.exam.course_name }}</td>
          <td>{{ result.marks_obtained }}</td>
          <td>{{ result.attempt_time }}</td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="3">No results found.</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}

templates/teacher/teacher_view_assignment.html
<!-- assignments/templates/assignments/teacher/teacher_view_assignment.html -->
{% extends 'teacher/teacherbase.html' %}
{% block content %}
{% load static %}

<head>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

  <style media="screen">
    a:link {
      text-decoration: none;
    }

    h6 {
      text-align: center;
    }

    .row {
      margin: 100px;
    }
  </style>
</head>
<br><br>
<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h6 class="panel-title">Assignments</h6>
    </div>
    <table class="table table-hover table-bordered" id="dev-table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Due Date</th>
          <th>Course</th>
          <th>Grade</th>
          <th>Required Keywords</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for assignment in assignments %}
        <tr>
          <td>{{ assignment.title }}</td>
          <td>{{ assignment.description }}</td>
          <td>{{assignment.course}}</td>
          <td>{{assignment.marks}}</td>
          <td>{{ assignment.due_date|date:"M d, Y H:i" }}</td>
          <td>{{ assignment.required_keywords }}</td>
          <td>
            <a class="btn btn-danger btn-xs" style="border-radius: 0%;" href="{% url 'teacher:teacher-delete-assignment' assignment.id %}">
              <span class="glyphicon glyphicon-trash"></span>
            </a>
          </td>
        </tr>
         {% empty %}
        <tr>
            <td colspan="5">No assignments available.</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock content %}

templates/teacher/teacher_view_marks.html
{% extends 'teacher/teacherbase.html' %}
{% block content %}
{% load static %}

<head>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

  <style>
    a:link {
      text-decoration: none;
    }

    h6 {
      text-align: center;
    }

    .row {
      margin: 100px;
    }
  </style>
</head>

<br><br>
<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h6 class="panel-title">Exams</h6>
    </div>
    <table class="table table-hover table-bordered" id="dev-table">
      <thead>
        <tr>
          <th>Exam Name</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for course in courses %}
        <tr>
          <td>{{ course.course_name }}</td>
          <td>
            <a class="btn btn-danger btn-sm" style="border-radius: 0%;" href="{% url 'teacher:teacher-check-marks' course.id %}">
              <span class="glyphicon glyphicon-eye-open"></span> View Marks
            </a>
          </td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="2">No exams found.</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<br><br><br><br><br><br>
{% endblock content %}

templates/teacher/teacher_view_student_marks.html
{% extends 'teacher/teacherbase.html' %}
{% block content %}
{% load static %}

<head>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

  <style>
    a:link {
      text-decoration: none;
    }

    h6 {
      text-align: center;
    }

    .row {
      margin: 100px;
    }
  </style>
</head>
<br><br>
<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h6 class="panel-title">Registered Students</h6>
    </div>
    <table class="table table-hover table-bordered" id="dev-table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Photo</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for student in students %}
        <tr>
          <td>{{ student.get_name }}</td>
          <td><img src="{% static student.profile_pic.url %}" alt="Profile Pic" height="40px" width="40px" /></td>
          <td>
            <a class="btn btn-primary btn-sm" style="border-radius: 0%;" href="{% url 'teacher:teacher-view-marks' student.id %}">
              <span class="glyphicon glyphicon-eye-open"></span> View Marks
          </a>
          </td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="3">No registered students found.</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock content %}